### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by thomaseizinger** [snap-ci/sample-conditional-stages#2]
Hi,

is it planned to actually add an example of how to configure a conditional stage in snap?

Regards,
Thomas

**Comment by ankitsri11** [comment]
Hi Thomas,

We just added a sample build on Snap. You can have a look here : https://snap-ci.com/snap-ci/sample-conditional-stages/branch/master/logs/defaultPipeline/10/BUILD?back_to=build_history

Regards,
Ankit
